version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/

permissions:
  - object: scripts/
    pattern: "**"
    owner: root
    group: root
    mode: 755


hooks:
 
BeforeInstall:
  - location: scripts/install_dependencies.sh
    timeout: 180
    runas: root
  - location: scripts/start_server.sh
    timeout: 180
    runas: root
    
