version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/

permissions:
  - object: /var/www/html/scripts/
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 755

hooks:
 
BeforeInstall:
  - location: scripts/install_dependencies.sh
    timeout: 180
    runas: ec2-user
    
