version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
hooks:
  ApplicattionStop:
    - location: scripts/stop_server.sh
      timeout: 300
      
AfterInstall:
  - location: scripts/after_install.sh
    timeout: 300
    
BeforeInstall:
  - location: scripts/install_dependencies.sh
    timeout: 300
    
ApplicationStart:
  - location: scripts/start_server.sh
    timeout: 300
    
ValidateService:
  - location: scrpts/validate_service.sh
    timeout: 300
