version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/
    
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 644
hooks:
  ApplicattionStop:
    - location: scripts/stop_server.sh
      timeout: 180
      runas: ec2-user
      
AfterInstall:
  - location: scripts/after_install.sh
    timeout: 180
    runas: ec2-user
    
BeforeInstall:
  - location: scripts/install_dependencies.sh
    timeout: 180
    runas: ec2-user
    
ApplicationStart:
  - location: scripts/start_server.sh
    timeout: 180
    runas: ec2-user
    
ValidateService:
  - location: scrpts/validate_service.sh
    timeout: 180
    runas: ec2-user
